/**
 * 
 */
package com.spring.hotel.management.system.hotel.reservation.system.util;

/**
 * @author Vikas Ramesh Kondvilkar
 * @className RuleEnum.java
   @created 18-Oct-2020
 */
public enum RuleEnum {
	NOT_EMPTY, CUSTOMER_NOT_EXIST, SIX_DIGIT_PASSWORD, WRONG_PASSWORD, CONTACT_NUMBER, DEACTIVATE_USER, MISMATCH_PASSWORD, USERID_NOT_PRESENT, MANDATORY_FIELDS_NOT_EXIST, ISO_DATE, ID_NOT_EXIST_IN_DB, IS_NUMBER, MANDATORY_FIELDS_NOT_EXIST_SEARCH, ROOM_BOOKING_AFTER_SIX_MONTH, PREVIOUS_DATE_SELECTED, WRONG_DATE_SELECTED, WRONG_CHECK_OUT_DATE_SELECTED, ROOM_NOT_AVAILABLE, ACCESS_DENIED
}
